name: dp-transformers
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - filelock=3.9.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.10.12
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtriton=2.0.0
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alembic==1.11.2
      - async-timeout==4.0.3
      - attrs==23.1.0
      - azure-common==1.1.28
      - azure-core==1.29.2
      - azure-identity==1.14.0
      - azure-mgmt-core==1.4.0
      - azure-storage-blob==12.13.0
      - azureml-mlflow==1.52.0
      - blinker==1.6.2
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - contourpy==1.1.0
      - cryptography==41.0.3
      - cycler==0.11.0
      - databricks-cli==0.17.7
      - datasets==2.14.4
      - dill==0.3.7
      - docker==6.1.3
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - flask==2.3.2
      - fonttools==4.42.0
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - greenlet==2.0.2
      - gunicorn==21.2.0
      - huggingface-hub==0.19.4
      - idna==3.4
      - importlib-metadata==6.8.0
      - iniconfig==2.0.0
      - isodate==0.6.1
      - itsdangerous==2.1.2
      - joblib==1.3.2
      - jsonpickle==3.0.2
      - kiwisolver==1.4.4
      - mako==1.2.4
      - markdown==3.4.4
      - matplotlib==3.7.2
      - mlflow==2.6.0
      - mlflow-skinny==2.6.0
      - msal==1.23.0
      - msal-extensions==1.0.0
      - msrest==0.7.1
      - multidict==6.0.4
      - multiprocess==0.70.15
      - numpy==1.25.2
      - oauthlib==3.2.2
      - opacus==1.4.0
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.3
      - peft==0.4.0
      - pillow==10.0.0
      - pluggy==1.2.0
      - portalocker==2.7.0
      - protobuf==4.24.0
      - prv-accountant==0.1.1.post1
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pycparser==2.21
      - pyjwt==2.8.0
      - pyparsing==3.0.9
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - safetensors==0.3.2
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - six==1.16.0
      - smmap==5.0.0
      - sqlalchemy==2.0.19
      - sqlparse==0.4.4
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - tomli==2.0.1
      - tqdm==4.66.1
      - transformers==4.36.1
      - tzdata==2023.3
      - urllib3==1.26.16
      - websocket-client==1.6.1
      - werkzeug==2.3.7
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2
